flamework/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('flamework_app.urls', namespace='flamework_app')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flamework_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mypage/$', views.mypage, name='mypage'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_idea/$', views.register_idea, name='register_idea'),
    url(r'^search/$', views.search, name='search'),
    url(r'^engineer_idea_detail/(?P<pk>\d+)/$', views.engineer_idea_detail, name='engineer_idea_detail'),
    url(r'^designer_idea_detail/(?P<pk>\d+)/$', views.designer_idea_detail, name='designer_idea_detail'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^wish/$', views.wish, name='wish'),
    url(r'^onsale/$', views.onsale, name='onsale'),
    url(r'^confirming/$', views.confirming, name='confirming'),
    url(r'^sale_request/$', views.sale_request, name='sale_request'),
    url(r'^sale_request_submitted/$', views.sale_request_submitted, name='sale_request_submitted'),
    url(r'^buy_request/$', views.buy_request, name='buy_request'),
    url(r'^buy_request_submitted/$', views.buy_request_submitted, name='buy_request_submitted'),
    url(r'^onsale_list/$', views.onsale_list, name='onsale_list'),
    url(r'^submitted_buy_request_list/$', views.submitted_buy_request_list, name='submitted_buy_request_list'),
    url(r'^edit_onsale/$', views.edit_onsale, name='edit_onsale'),
    url(r'^wish_list/$', views.wish_list, name='wish_list'),
    url(r'^edit_wish/$', views.edit_wish, name='edit_wish'),
    url(r'^submitted_sale_request_list/$', views.submitted_sale_request_list, name='submitted_sale_request_list'),
    url(r'^sell/$', views.sell, name='sell'),
    url(r'^sell_confirm/$', views.sell_confirm, name='sell_confirm'),
    url(r'^sell_completed/$', views.sell_completed, name='sell_completed'),
]

flamework_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import requests
import uuid


class User(AbstractUser):
    pass


class UserInfo(models.Model):
    ENGINEER = 'engineer'
    DESIGNER = 'designer'
    USER_TYPE = (
        (ENGINEER, 'エンジニア'),
        (DESIGNER, 'デザイナー'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    user_type = models.CharField(max_length=16, null=False, choices=USER_TYPE, default=ENGINEER)
    weekday_daytime = models.BooleanField(null=False, default=False)
    weekday_night = models.BooleanField(null=False, default=False)
    weekends_daytime = models.BooleanField(null=False, default=False)
    weekends_night = models.BooleanField(null=False, default=False)
    address = models.CharField(max_length=32, null=False, blank=False)
    zipcode = models.CharField(max_length=16, null=False, blank=False)

    def digest_address(self, address):
        url = 'http://zipcoda.net/api'
        r = requests.get(url, params={'address': address})
        self.zipcode = r.json()['items'][0]['zipcode']
        r = requests.get(url, params={'zipcode': self.zipcode})
        self.address = r.json()['items'][0]['address']
        self.save()

    def get_zip_distance(self, other):
        if self.zipcode == other:
            return 0
        for distance in range(1, len(self.zipcode)):
            if self.zipcode[:-distance] == other[:-distance]:
                return distance
        return len(self.zipcode)


class Idea(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=32, null=False)
    description = models.TextField(null=False)
    updated_at = models.DateTimeField(auto_now_add=True, null=False)

    class Meta:
        get_latest_by = 'updated_at'

    @property
    def images(self):
        return IdeaImage.objects.filter(idea=self)

    @property
    def image_num(self):
        return IdeaImage.objects.filter(idea=self).count()


class IdeaImage(models.Model):
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    image = models.ImageField()
    created_at = models.DateTimeField(null=False, auto_now=True)


class EngineerIdea(Idea):
    pass


class DesignerIdea(Idea):

    def __str__(self):
        return self.title


class Like(models.Model):
    liked_to = models.ForeignKey(User, on_delete=models.CASCADE)
    liked_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes", related_query_name="like",)
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = 'created_at'

flamework_app/forms.py
from django import forms
from .models import UserInfo, DesignerIdea


class DesignerIdeaForm(forms.ModelForm):
    class Meta:
        model = DesignerIdea
        fields = ['title', 'description']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['weekday_daytime', 'weekday_night', 'weekends_daytime', 'weekends_night', 'user_type']

flamework_app/views.py
from django.shortcuts import render, redirect
from flamework_app.models import DesignerIdea, EngineerIdea, IdeaImage, UserInfo, User
from .forms import DesignerIdeaForm, UserInfoForm
from django.contrib.auth import authenticate, login
import uuid


def index(request):
    return render(request, 'flamework_app/index.html')


def register(request):
    if request.method == 'POST':
        user_name = uuid.uuid4().hex[:10]
        email = uuid.uuid4().hex[:10]
        password = uuid.uuid4().hex[:10]
        user = User.objects.create_user(user_name,
                                        '{}@thebeatles.com'.format(email),
                                        password)
        user = authenticate(request, username=user_name, password=password)
        login(request, user)

        f = DesignerIdeaForm(request.POST)
        design_idea = f.save(commit=False)
        design_idea.user = request.user
        design_idea.save()

        f = UserInfoForm(request.POST)
        user_info = f.save(commit=False)
        user_info.user = request.user
        user_info.digest_address(request.POST['address'])

        for img in request.FILES.getlist('image', []):
            IdeaImage.objects.create(idea=design_idea, image=img)
        return redirect('/mypage/')

    elif request.method == 'GET':
        form = UserInfoForm()
        return render(request, 'flamework_app/register.html', {'form': form})


def register_idea(request):
    if request.method == 'POST':
        f = DesignerIdeaForm(request.POST)
        design_idea = f.save(commit=False)
        design_idea.user = request.user
        design_idea.save()

        for img in request.FILES.getlist('image', []):
            IdeaImage.objects.create(idea=design_idea, image=img)
        return redirect('/mypage/')

    elif request.method == 'GET':
        form = UserInfoForm()
        return render(request, 'flamework_app/register.html', {'form': form})


def mypage(request):
    return render(request, 'flamework_app/mypage.html')


def search(request):

    def distance(idea: DesignerIdea):
        return idea.user.userinfo.get_zip_distance(request.user.userinfo.zipcode)

    target = request.GET.get('target', 'designer')

    if target == 'designer':
        ideas = list(sorted(DesignerIdea.objects.all(), key=lambda x: x.image_num, reverse=True))
        ideas = list(sorted(ideas, key=lambda i: distance(i)))
        context = {
            'ideas': ideas
        }
        return render(request, 'flamework_app/search_designers.html', context)
    else:
        ideas = EngineerIdea.objects.all()
        context = {
            'ideas': ideas
        }
        return render(request, 'flamework_app/search_engineers.html', context)


def engineer_idea_detail(request, pk):
    # idea = EngineerIdea.objects.get(id=pk)
    # context = {'idea': idea}
    return render(request, 'flamework_app/engineer_idea_detail.html')


def designer_idea_detail(request, pk):
    idea = DesignerIdea.objects.get(id=pk)
    images = IdeaImage.objects.filter(idea=idea)
    context = {'idea': idea, 'images': images}
    return render(request, 'flamework_app/designer_idea_detail.html', context)


def signup(request):
    return render(request, 'flamework_app/signup.html')


def signin(request):
    return render(request, 'flamework_app/signin.html')


def wish(request):
    return render(request, 'flamework_app/wish.html')


def onsale(request):
    return render(request, 'flamework_app/onsale.html')


def confirming(request):
    return render(request, 'flamework_app/confirming.html')


def sale_request(request):
    return render(request, 'flamework_app/sale_request.html')


def sale_request_submitted(request):
    return render(request, 'flamework_app/sale_request_submitted.html')


def buy_request(request):
    return render(request, 'flamework_app/buy_request.html')


def buy_request_submitted(request):
    return render(request, 'flamework_app/buy_request_submitted.html')


def onsale_list(request):
    return render(request, 'flamework_app/onsale_list.html')


def submitted_buy_request_list(request):
    return render(request, 'flamework_app/submitted_buy_request_list.html')


def edit_onsale(request):
    return render(request, 'flamework_app/edit_onsale.html')


def wish_list(request):
    return render(request, 'flamework_app/wish_list.html')


def edit_wish(request):
    return render(request, 'flamework_app/edit_wish.html')


def submitted_sale_request_list(request):
    return render(request, 'flamework_app/submitted_sale_request_list.html')


def sell(request):
    return render(request, 'flamework_app/sell.html')


def sell_confirm(request):
    return render(request, 'flamework_app/sell_confirm.html')


def sell_completed(request):
    return render(request, 'flamework_app/sell_completed.html')

flamework_app/templates/flamework_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>flamework_app</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'flamework_app/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'flamework_app/css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css"
          integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'flamework_app/css/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'flamework_app/css/slick-theme.css' %}"/>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

{#<nav class="navbar navbar-inverse navbar-fixed-top">#}
{#    <div class="container">#}
{#        <div class="navbar-header">#}
{#            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"#}
{#                    aria-expanded="false" aria-controls="navbar">#}
{#                <span class="sr-only">Toggle navigation</span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}
{#            <a class="navbar-brand" href="{% url 'flamework_app:index' %}">Flamework</a>#}
{#        </div>#}
{#        <div id="navbar" class="navbar-collapse collapse">#}
{#            <form class="navbar-form navbar-left" action="{% url 'flamework_app:search' %}" method="get">#}
{#                <div class="form-group">#}
{#                    <input type="text" placeholder="キーワードから探す" class="form-control">#}
{#                </div>#}
{#                <button type="submit" class="btn">検索</button>#}
{#            </form>#}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li><a href="{% url 'flamework_app:mypage' %}">mypage</a></li>#}
{#                <li><a href="{% url 'flamework_app:signin' %}">Sign In</a></li>#}
{#                <li><a href="{% url 'flamework_app:signup' %}">Sign Up</a></li>#}
{#            </ul>#}
{#        </div><!--/.navbar-collapse -->#}
{#    </div>#}
{#</nav>#}
<div id="header">
    <div class="left-content">
        <a href="./">
            <img src="{% static 'flamework_app/img/header/logo.png' %}" class="logo">
        </a>
    </div>
    <div class="right-content right-margin">
        <img src="{% static 'flamework_app/img/header/my_page-01.png' %}" class="menu-banner" alt="My Page">
    </div>
    <div class="right-content left-margin">
        <img src="{% static 'flamework_app/img/header/flame_list-01.png' %}" class="menu-banner" alt="Flame List">
    </div>

</div>

{% block content %}
{% endblock %}

<hr>

<footer>
    <p align="center">&copy; 2017 いっぱい</p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'flamework_app/js/slick.min.js' %}"></script>
<script src="{% static 'flamework_app/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>

<script>
    $(document).ready(function () {
        $('.image-slide').slick({
             accessibility: true
        });
    });
</script>
</body>
</html>

flamework_app/templates/flamework_app/buy_request_submitted.html
{% extends 'flamework_app/base.html' %}
{% block content %}
  <div class="container" style="margin-top: 60px;width:600px;">

  <div class="jumbotron text-center">
    <div>購入申請をしました</div>
    <div>
      お金おろしとけよ
    </div>
  </div>

  </div>
{% endblock %}

flamework_app/templates/flamework_app/designer_idea_detail.html
{% extends 'flamework_app/base.html' %}
{% load static %}
{% block content %}
    <div class="container" style="margin-top: 60px; width: 700px;">

        <div class="image-slide">
            {% for image in images %}
                <img src="{{ image.image.url }}" alt="">
            {% endfor %}
        </div>


        <div id="description">
            <h3 id="idea-title">{{ idea.title }}</h3>

            <p id="idea-description">{{ idea.description }}</p>

            <p><img src="{% static 'flamework_app/img/user_icon.png' %}" height="80px" alt=""></p>

            <p>
                <small>デザイナー</small>
                <br>小野寺ゆうたろう
            </p>
            <p>年齢：20歳　デザイナー歴：２ヶ月　活動時間：17:00~　住まい：渋谷区</p>
            <a href="{% url 'flamework_app:search' %}">
                <button class="btn btn-sm btn-warning">コンタクト申請する</button>
            </a>

        </div>
    </div>
{% endblock %}

flamework_app/templates/flamework_app/engineer_idea_detail.html
{% load staticfiles %}
<html>
<body>
<a href="{% url 'flamework_app:mypage' %}">
<img src="{% static 'flamework_app/img/pera/エンジニア詳細-01.png' %}" style="max-height: 100%;max-width: 100%;">
</a>
</body>
</html>

flamework_app/templates/flamework_app/mypage_base.html
{% extends 'flamework_app/base.html' %}
{% block content %}

    <div class="container-fluid" style="margin-top: 60px">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="{% url 'flamework_app:mypage' %}">マイページ<span class="sr-only">(current)</span></a></li>
            <li><a href="#">お知らせ<span class="badge">2</span></a></li>
            <li><a href="#">やることリスト<span class="badge">2</span></a></li>
            <li><a href="#">購入申請中<span class="badge">2</span></a></li>
            <li><a href="#">売却申請中<span class="badge">2</span></a></li>
            <li><a href="{% url 'flamework_app:sell' %}">出品する</a></li>
            <li><a href="{% url 'flamework_app:onsale_list' %}">出品中<span class="badge">1</span></a></li>
            <li><a href="{% url 'flamework_app:submitted_buy_request_list' %}">未承認購入申請<span class="badge">4</span></a></li>
            <li><a href="{% url 'flamework_app:wish_list' %}">欲しいものリスト<span class="badge">3</span></a></li>
            <li><a href="{% url 'flamework_app:submitted_sale_request_list' %}">未承認売却申請<span class="badge">2</span></a></li>
            <li><a href="#">ニュース一覧<span class="badge">2</span></a></li>
            <li><a href="#">ガイド<span class="badge">2</span></a></li>
            <li><a href="#">お問い合わせ<span class="badge">2</span></a></li>
          </ul>
        </div>

        <div class="col-sm-9 main">
          {% block main %}
          {% endblock %}
        </div>
      </div>
    </div>

{% endblock %}

flamework_app/templates/flamework_app/onsale.html
{% extends 'flamework_app/base.html' %}
{% block content %}
  <div class="container" style="margin-top: 60px;width:600px;">

  <div class="jumbotron text-center">
    <h2>認知心理学の教科書</h2>
    <h3>買取価格: 500円</h3>
    <form class="form" action="{% url 'flamework_app:buy_request' %}" method="get">
      <button type="submit" class="btn btn-primary">買いたい</button>
    </form>
  </div>

  </div>
{% endblock %}

flamework_app/templates/flamework_app/onsale_list.html
{% extends 'flamework_app/mypage_base.html' %}
{% block main %}
  <div class="container" style="margin-top: 60px">
    <h2>売り出し中商品一覧</h2>
    <div class="col-sm-4">
      <a href="{% url 'flamework_app:wish' %}">
        <h3>Wanted!</h3>
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
        アルゴの教科書
        1000円
      </a>
    </div>
  </div>
{% endblock %}

flamework_app/templates/flamework_app/register_idea.html
{% extends 'flamework_app/base.html' %}

{% block content %}
  <div class="container" style="margin-top: 60px;width: 300px;">

    <form class="form" action="{% url 'flamework_app:register' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <h2 class="form-signin-heading">アイデア入力</h2>
      <label for="title" class="sr-only">タイトル</label>
      <input id="title" name="title" class="form-control" required autofocus>
      <label for="description" class="sr-only">説明</label>
      <textarea id="description" name="description" class="form-control" required></textarea>
      <input name="image" type="file" value="画像1">
      <input name="image" type="file" value="画像2">
      <input name="image" type="file" value="画像3">
      <input name="image" type="file" value="画像4">
      <input name="image" type="file" value="画像5">
      <button class="btn btn-lg btn-primary btn-block" type="submit">登録</button>
    </form>

  </div>
{% endblock %}

flamework_app/templates/flamework_app/sale_request_submitted.html
{% extends 'flamework_app/base.html' %}
{% block content %}
  <div class="container" style="margin-top: 60px;width:600px;">

  <div class="jumbotron text-center">
    <div>売りつけ申請をしました</div>
    <div>
      果報は寝て待て
    </div>
  </div>

  </div>
{% endblock %}

flamework_app/templates/flamework_app/search_designers.html
{% extends 'flamework_app/base.html' %}

{% block content %}
<div class="container" style="margin-top: 60px">
    {% for idea in ideas %}
        <div class="col-sm-4">
            <a href="{% url 'flamework_app:designer_idea_detail' idea.id %}">
                <h3>{{ idea.title }}</h3>
            </a>
            <div class="image">
                <div class="img-center">
                    <img src="{{ idea.images.0.image.url }}"
                         width="200"
                         height="200" class="img-responsive trim" alt="Generic placeholder thumbnail">
                    <div class="image-footer">
                        <p class="renew-date">2017年9月17日</p>
                        <button class="flame-btn btn btn-warning btn-xs">Flame!</button>
                    </div>
                </div>
            </div>
            {{ idea.description }}
        </div>
    {% endfor %}
</div>
{% endblock %}

flamework_app/templates/flamework_app/sell_completed.html
{% extends 'flamework_app/base.html' %}
{% block content %}
  <div class="container jumbotron" style="margin-top: 60px;width: 600px;">

  <div>
    <h2>商品の出品が完了しました</h2>
    お疲れ様でした
  </div>

  </div>
{% endblock %}

flamework_app/templates/flamework_app/signin.html
{% extends 'flamework_app/base.html' %}
{% block content %}
  <div class="container" style="margin-top: 60px;width: 300px;">

    <form class="form">
      <h2 class="form-signin-heading">sign in</h2>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign In</button>
    </form>

  </div>
{% endblock %}

flamework_app/templates/flamework_app/signup.html
{% extends 'flamework_app/base.html' %}
{% block content %}
  <div class="container" style="margin-top: 60px;width: 300px;">

    <form class="form" action="{% url 'flamework_app:confirming' %}" method="post">
      {% csrf_token %}
      <h2 class="form-signin-heading">sign up</h2>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
    </form>

  </div>
{% endblock %}

flamework_app/templates/flamework_app/submitting_buy_request_list.html
{% extends 'flamework_app/mypage_base.html' %}
{% block main %}
  <div class="container" style="margin-top: 60px">
    <h2>未承認購入申請</h2>

    <div class="row">
      <div class="col-sm-3">
        <a href="{% url 'flamework_app:edit_onsale' %}">
          <h3>Wanted!</h3>
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
          推奨機
          1000円
        </a>
      </div>
      <div class="col-sm-9">
        <h3>売却申請</h3>
        <ul>
          <li class="list-inline"><a href="#">2017/05/04 「来週の月曜の昼休みに１階円卓にてどうでしょうか」</a>
            <form style="display: inline">
              <button class="btn btn-success" type="submit">承認</button>
            </form>
            <form style="display: inline">
              <button class="btn btn-danger" type="submit">リジェクト</button>
            </form>
          </li>
          <li class="list-inline"><a href="#">2017/05/04 「来週の火曜の昼休みに１階円卓にてどうでしょうか」</a>
            <form style="display: inline">
              <button class="btn btn-success" type="submit">承認</button>
            </form>
            <form style="display: inline">
              <button class="btn btn-danger" type="submit">リジェクト</button>
            </form>
          </li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <a href="{% url 'flamework_app:edit_onsale' %}">
          <h3>Wanted!</h3>
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
          Arduino
          1000円
        </a>
      </div>
      <div class="col-sm-9">
        <h3>売却申請</h3>
        <ul>
          <li class="list-inline"><a href="#">2017/05/04 「来週の月曜の昼休みに１階円卓にてどうでしょうか」</a>
            <form style="display: inline">
              <button class="btn btn-success" type="submit">承認</button>
            </form>
            <form style="display: inline">
              <button class="btn btn-danger" type="submit">リジェクト</button>
            </form>
          </li>
          <li class="list-inline"><a href="#">2017/05/04 「来週の火曜の昼休みに１階円卓にてどうでしょうか」</a>
            <form style="display: inline">
              <button class="btn btn-success" type="submit">承認</button>
            </form>
            <form style="display: inline">
              <button class="btn btn-danger" type="submit">リジェクト</button>
            </form>
          </li>
        </ul>
      </div>
    </div>

  </div>

{% endblock %}